# UART signals
set_property PACKAGE_PIN BC28 [ get_ports "uart_rst_n" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "uart_rst_n" ]
set_property PACKAGE_PIN BE28 [ get_ports "uart_txd" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "uart_txd" ]
set_property PACKAGE_PIN BF29 [ get_ports "uart_rts" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "uart_rts" ]
set_property PACKAGE_PIN BD28 [ get_ports "uart_rxd" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "uart_rxd" ]
set_property PULLUP TRUE [ get_ports "uart_rxd" ]
set_property PACKAGE_PIN BF28 [ get_ports "uart_cts" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "uart_cts" ]
